# Python, Лекция 12.

[Оригинал](https://github.com/DanielShinoda/ami_python_25_lectures/blob/main/lectures/12.%20NumPy.%20Pandas/Lecture_12.ipynb) лекции.

Сегодня мы поговорим о модулях [NumPy](https://numpy.org/) и [Pandas](https://pandas.pydata.org/): основа анализа данных и машинного обучения.

## NumPy

Библеотека NumPy предоставляет следующие возможности:
* работать с многомерными массивами (включая матрицы)
* производить быстрое вычисление математических функций на многомерных массивах

Ядром пакета NumPy является объект `ndarray`.

Важные отличия между NumPy arrays и Python sequences:

* NumPy array имеет фиксированную длину, которая определяется в момент его создания (в отличие от Python lists, которые могут расти динамически)

* Элементы в NumPy array должны быть одного типа

* Можно выполнять операции непосредственно над NumPy arrays

То есть ближайшая знакомая нам структура к `ndarray` - это `array`, в который мы тоже передаем конкретный тип.

In [1]:
#%pip install numpy

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([1, 2, 3, 4, 5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
np.float32([1, 2, 3, 4, 5])

array([1., 2., 3., 4., 5.], dtype=float32)

### Конструкторы

Есть несколько конструкторов:

- `arange` - аналог `range`

- `linspace` - разбивает отрезок на `n - 1` интервал

- `logspace` - разбивает отрезок по логарифмической шкале

- `zeros` - матрица, заполненный нулями заданной размерности

- `ones` - матрица, заполненный единицами заданной размерности

- `diag` - диагональная матрица

- `empty` - матрица, проинициализированной размерности для дальнейшего заполнения

In [6]:
np.arange(0, 3, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9])

In [7]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
array = np.ones(
    (
        2,
        3,
    )
)
print(
    "Размерность массива - %s, количество размерностей - %d" % (array.shape, array.ndim)
)
array

Размерность массива - (2, 3), количество размерностей - 2

array([[1., 1., 1.],
       [1., 1., 1.]])

Чему равны `ndim` и `shape` в следующих случаях?

In [12]:
print(np.diag([1, 2, 3]).shape, np.diag([1, 2, 3]).ndim)
print(np.zeros((5, 5, 5)).shape, np.zeros((5, 5, 5)).ndim)

(3, 3) 2
(5, 5, 5) 3

Метод `reshape` позволяет преобразовать размерности матрицы без изменения данных внутри нее.

In [13]:
array = np.arange(0, 6, 0.5)
array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [14]:
new_array = array.reshape((2, 6))
new_array

array([[0. , 0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. , 5.5]])

In [15]:
new_array = array.reshape((4, 3))
new_array

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [16]:
array[0] = -1
array[0], new_array[0][0]

(np.float64(-1.0), np.float64(-1.0))

In [17]:
raveled_array = new_array.ravel()
raveled_array

array([-1. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5])

Что будет тут?

In [18]:
print(np.ravel(np.diag([1, 2])))

[1 0 0 2]

In [19]:
print(np.reshape(np.diag([1, 2]), [1, 4]))

[[1 0 0 2]]

### Индексация и нарезание

Базовое нарезание расширяет подход питона к нарезанию на n-мерное пространство. В качестве входных аргументов в слайс могут применяться еще и `Ellipsis` и `np.newaxis`. В слайсе мы идем по следующей формуле:

$
0 \leq n_i < d_i
$, где $d_i$ - размерность массива i-го пространства.

In [20]:
print(array[0])
print(array[-1])
print(array[1:-1])
print(array[1:-1:2])
print(array[::-1])
print(array.shape)
print(array[1:20])

-1.0
5.5
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[0.5 1.5 2.5 3.5 4.5]
[ 5.5  5.   4.5  4.   3.5  3.   2.5  2.   1.5  1.   0.5 -1. ]
(12,)
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]

Все слайсы являются `view` над исходным массивом:

In [21]:
b = array[0]
print(b)
array[0] = 10
print(b)

-1.0
-1.0

In [22]:
print(array[None, 0:, None].ndim, array[None, 0:, None].shape)
array[None, 0:, None]

3 (1, 12, 1)

array([[[10. ],
        [ 0.5],
        [ 1. ],
        [ 1.5],
        [ 2. ],
        [ 2.5],
        [ 3. ],
        [ 3.5],
        [ 4. ],
        [ 4.5],
        [ 5. ],
        [ 5.5]]])

Индексы и срезы в многомерных массивах не разделяются квадратными скобками - пишем через запятую.

In [23]:
array[[0, 2, 4, 6, 8, 10]]

array([10.,  1.,  2.,  3.,  4.,  5.])

In [24]:
array[[True, False, True, False, True, False, True, False, True, False, True, False]]

array([10.,  1.,  2.,  3.,  4.,  5.])

In [25]:
x = np.array([[1, 2, 3]])
y = np.array([1, 2, 3])

print(x.shape, y.shape)

print(np.array_equal(x, y))
print(np.array_equal(x, y[None, :]))

(1, 3) (3,)
False
True

### Способы индексации пространств

`Ellipsis` расширяет количество объектов в слайсе до `ndim`. В слайсе может быть только один `Ellipsis`.

In [26]:
x = np.array([[[1], [2], [3]], [[4], [5], [6]]])
x[...], x[..., 0], x[0, ...], x[1, 1, 0]

(array([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1],
        [2],
        [3]]),
 np.int64(5))

Более того:

In [27]:
x[:, :, 0] == x[..., 0], x[:, :, 0]

(array([[ True,  True,  True],
        [ True,  True,  True]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

`np.newaxis` - объект, расширяющий размерность на один юнит. Изменённая пространство - индекс `np.newaxis` в слайсе. На самом деле `np.newaxis` - обертка над `None` и можно использовать `None`.

In [28]:
x[:, np.newaxis, :, :], x[:, np.newaxis, :, :].shape, x[:, None, :, :].shape

(array([[[[1],
          [2],
          [3]]],


        [[[4],
          [5],
          [6]]]]),
 (2, 1, 3, 1),
 (2, 1, 3, 1))

Какое же практическое применение?

In [29]:
x = np.arange(5)
x, x[:, np.newaxis] + x[np.newaxis, :]

(array([0, 1, 2, 3, 4]),
 array([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]]))

In [30]:
x[:, np.newaxis], x[np.newaxis, :]

(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 array([[0, 1, 2, 3, 4]]))

### Индексация целочисленными массивами

In [31]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [32]:
x[np.array([3, 3, 1, 8])], x[np.array([3, 3, -3, 8])]

(array([7, 7, 9, 2]), array([7, 7, 4, 2]))

Если индексы выходят за границу, то пробрасывается `IndexError`

In [33]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [34]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

В этом примере у нас индексовые массивы имеют одинаковые размерность, соответственно мы достаем следующие элементы:
`y[0, 0]`, `y[2, 1]`, `y[4, 2]`

In [35]:
y[np.array([0, 2, 4]), np.array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,)

In [36]:
y[np.array([0, 2, 4]), 1]

array([ 1, 15, 29])

In [37]:
y[np.array([0, 2, 4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

### Broadcasting

Этот термин объясняет как numpy работает с массивами различных размерностей во время арифметических операций. Массив поменьше "броадкастится" к размерности большего массива, чтобы можно было выполнять операции. Броадкастинг происходит в С, а не в питоне, а следовательно эффективное использование памяти без лишних копий, но есть кейсы где плохо использовать броадкастинг.

In [38]:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [39]:
a = np.array([1.0, 2.0, 3.0])
b = 2
a * b

array([2., 4., 6.])

Тут применяется растяжение: `b` дополняется до размерности `a`, чтобы проделать операцию поэлемнетного умножения:

***Картинка в [оригинале](https://github.com/DanielShinoda/ami_python_25_lectures/blob/main/lectures/12.%20NumPy.%20Pandas/Lecture_12.ipynb) данной лекции.***

Общий правила броадкаста:

Когда numpy работает с двумя массивами, он сравнивает их размерности поэлементно, начиная с самой правой и идя к левой размерности. Две размерности сравнимы если они одинаковы или одна из них равна единице.

По правилу мы расширяем размерность до большей если одна из них является единицей или отсутствует:

***Картинка в [оригинале](https://github.com/DanielShinoda/ami_python_25_lectures/blob/main/lectures/12.%20NumPy.%20Pandas/Lecture_12.ipynb) данной лекции.***

***Картинка в [оригинале](https://github.com/DanielShinoda/ami_python_25_lectures/blob/main/lectures/12.%20NumPy.%20Pandas/Lecture_12.ipynb) данной лекции.***

In [40]:
a = np.array(
    [[0.0, 0.0, 0.0], [10.0, 10.0, 10.0], [20.0, 20.0, 20.0], [30.0, 30.0, 30.0]]
)
b = np.array([1.0, 2.0, 3.0])

a имеется размерность 4x3, b имеет размерность 1x3

In [41]:
a + b, (a + b).shape

(array([[ 1.,  2.,  3.],
        [11., 12., 13.],
        [21., 22., 23.],
        [31., 32., 33.]]),
 (4, 3))

Складывая два массива мы получили итоговую размерность 4x3.

***Картинка в [оригинале](https://github.com/DanielShinoda/ami_python_25_lectures/blob/main/lectures/12.%20NumPy.%20Pandas/Lecture_12.ipynb) данной лекции.***

***Картинка в [оригинале](https://github.com/DanielShinoda/ami_python_25_lectures/blob/main/lectures/12.%20NumPy.%20Pandas/Lecture_12.ipynb) данной лекции.***

In [42]:
import numpy as np

a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

***Картинка в [оригинале](https://github.com/DanielShinoda/ami_python_25_lectures/blob/main/lectures/12.%20NumPy.%20Pandas/Lecture_12.ipynb) данной лекции.***

### Индексация броадкастом

In [43]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [44]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
rows = np.array([[0, 0], [3, 3]], dtype=np.intp)
columns = np.array([[0, 2], [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [45]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
rows[:, np.newaxis]

array([[0],
       [3]])

In [46]:
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [47]:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

### Индексация булами

In [48]:
x = np.array([[1.0, 2.0], [np.nan, 3.0], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [49]:
x[~np.isnan(x)]

array([1., 2., 3.])

In [50]:
x = np.array([1.0, -1.0, -2.0, 3])
x

array([ 1., -1., -2.,  3.])

In [51]:
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

In [52]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [53]:
x[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [54]:
x = np.array([[0, 1], [1, 1], [2, 2]])
x

array([[0, 1],
       [1, 1],
       [2, 2]])

In [55]:
rowsum = x.sum(-1)
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [56]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
rows = (x.sum(-1) % 2) == 0
rows

array([False,  True, False,  True])

In [57]:
columns = [0, 2]
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

### Операции

In [58]:
x = np.arange(40).reshape(5, 2, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [59]:
x.mean(), np.mean(x)

(np.float64(19.5), np.float64(19.5))

In [60]:
x.mean(axis=0)

array([[16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [61]:
x.mean(axis=1)

array([[ 2.,  3.,  4.,  5.],
       [10., 11., 12., 13.],
       [18., 19., 20., 21.],
       [26., 27., 28., 29.],
       [34., 35., 36., 37.]])

In [62]:
x.mean(axis=2)

array([[ 1.5,  5.5],
       [ 9.5, 13.5],
       [17.5, 21.5],
       [25.5, 29.5],
       [33.5, 37.5]])

In [63]:
x.mean(axis=(0, 2))

array([17.5, 21.5])

In [64]:
x.mean(axis=(0, 1, 2))

np.float64(19.5)

### Конкатенация многомерных массивов

In [65]:
x = np.arange(10).reshape(5, 2)
y = np.arange(100, 120).reshape(5, 4)

In [66]:
x, y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111],
        [112, 113, 114, 115],
        [116, 117, 118, 119]]))

In [67]:
np.hstack((x, y)), np.hstack((x, y)).shape

(array([[  0,   1, 100, 101, 102, 103],
        [  2,   3, 104, 105, 106, 107],
        [  4,   5, 108, 109, 110, 111],
        [  6,   7, 112, 113, 114, 115],
        [  8,   9, 116, 117, 118, 119]]),
 (5, 6))

In [68]:
x = np.ones([2, 2])
y = np.zeros([2, 2])

In [69]:
np.hstack((x, y)), np.vstack((x, y))

(array([[1., 1., 0., 0.],
        [1., 1., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]]))

In [70]:
p = np.arange(1).reshape([1, 1, 1, 1])
p

array([[[[0]]]])

In [71]:
print("vstack: ", np.vstack((p, p)).shape)
print("hstack: ", np.hstack((p, p)).shape)
print("dstack: ", np.dstack((p, p)).shape)
print("concatenate: ", np.concatenate((p, p), axis=3).shape)

vstack:  (2, 1, 1, 1)
hstack:  (1, 2, 1, 1)
dstack:  (1, 1, 2, 1)
concatenate:  (1, 1, 1, 2)

### Типы

In [72]:
x = [1, 2, 70000]

In [73]:
np.array(x, dtype=np.float32)

array([1.e+00, 2.e+00, 7.e+04], dtype=float32)

In [74]:
np.array(x, dtype=np.uint16)

OverflowError: Python integer 70000 out of bounds for uint16

In [75]:
import numpy.typing as npt

* `npt.ArrayLike` - объекты, которые могут быть скастованы в `ndarray` (константы, последовательности, объекты с методом `\array`)
* `npt.DTypeLike` - объекты, которые могут быть скастованы в `np.dtype`
* `npt.NDArray` - массивы `np.ndarray` с определённым типом и неопределённой размерностью

In [76]:
# !pip install nb-mypy -qqq
!pip install nb-mypy --no-deps
!pip install mypy astor

Collecting nb-mypy
  Downloading nb_mypy-1.0.6-py3-none-any.whl.metadata (3.0 kB)
Downloading nb_mypy-1.0.6-py3-none-any.whl (7.8 kB)
Installing collected packages: nb-mypy
Successfully installed nb-mypy-1.0.6
Collecting mypy
  Downloading mypy-2.4.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting astor
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing_extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from mypy) (4.16.0)
Collecting mypy_extensions>=1.0.0 (from mypy)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=1.0.0 (from mypy)
  Downloading pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Collecting librt>=0.16.0 (from mypy)
  Downloading librt-0.16.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Collecting ast-serialize<1.0.0,>=0.11.2 (from mypy)
  Downloading ast_serialize-0.12.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Downloading mypy-2.4.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (15.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 67.1 MB/s eta 0:00:00
Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Downloading ast_serialize-0.12.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 54.6 MB/s eta 0:00:00
Downloading librt-0.16.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (531 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.7/531.7 kB 26.5 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pathspec-1.1.1-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 3.9 MB/s eta 0:00:00
Installing collected packages: pathspec, mypy_extensions, librt, astor, ast-serialize, mypy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nb-mypy 1.0.6 requires ipython<10,>=9.0, but you have ipython 7.34.0 which is incompatible.
nb-mypy 1.0.6 requires mypy<2,>=1, but you have mypy 2.4.0 which is incompatible.
Successfully installed ast-serialize-0.12.1 astor-0.8.1 librt-0.16.0 mypy-2.4.0 mypy_extensions-1.1.0 pathspec-1.1.1

In [77]:
%load_ext nb_mypy

Version 1.0.6
INFO:nb-mypy:Version 1.0.6

In [78]:
%nb_mypy On

In [79]:
def as_array(a: npt.ArrayLike) -> npt.NDArray[np.int_]:
    return np.array(a)


arr = as_array([1, 2, 3])

<cell>1: error: Name "npt" is not defined  [name-defined]
ERROR:nb-mypy:<cell>1: error: Name "npt" is not defined  [name-defined]
<cell>1: error: Name "np" is not defined  [name-defined]
ERROR:nb-mypy:<cell>1: error: Name "np" is not defined  [name-defined]
<cell>2: error: Name "np" is not defined  [name-defined]
ERROR:nb-mypy:<cell>2: error: Name "np" is not defined  [name-defined]

In [80]:
import numpy as np
import numpy.typing as npt


def as_array(a: npt.ArrayLike) -> npt.NDArray[np.int_]:
    return np.array(a)


as_array([1, 2, 3])

array([1, 2, 3])

In [81]:
import numpy as np
import numpy.typing as npt


def as_array(a: npt.ArrayLike) -> list[float]:
    return list(a)


as_array([1, 2, 3])

<cell>6: error: Argument 1 to "list" has incompatible type "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"; expected "Iterable[float]"  [arg-type]
ERROR:nb-mypy:<cell>6: error: Argument 1 to "list" has incompatible type "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"; expected "Iterable[float]"  [arg-type]

[1, 2, 3]

In [82]:
import numpy as np
import numpy.typing as npt


def as_array(a: npt.ArrayLike) -> npt.NDArray[np.float64]:
    return np.array(a)


class A:
    pass


as_array(A())

<cell>13: error: Argument 1 to "as_array" has incompatible type "A"; expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"  [arg-type]
ERROR:nb-mypy:<cell>13: error: Argument 1 to "as_array" has incompatible type "A"; expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"  [arg-type]

array(<__main__.A object at 0x7b86413057f0>, dtype=object)

In [83]:
%nb_mypy Off

## [Pandas](https://pandas.pydata.org/docs/)

Сейчас займемся с вами демографическими исследованиями и то, почему многие ведущие страны потихоньку вымирают в привычном нам виде.

In [84]:
import pandas as pd

In [85]:
!wget https://raw.githubusercontent.com/SergeyKorpachev/python_dirs/refs/heads/main/2026/Lectures/Lecture_12/global_population_stats_2024.csv

--2026-10-05 20:35:14--  https://raw.githubusercontent.com/SergeyKorpachev/python_dirs/refs/heads/main/2026/Lectures/Lecture_12/global_population_stats_2024.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9032 (8.8K) [text/plain]
Saving to: ‘global_population_stats_2024.csv’

global_population_s 100%[===================>]   8.82K  --.-KB/s    in 0s

2026-10-05 20:35:14 (17.3 MB/s) - ‘global_population_stats_2024.csv’ saved [9032/9032]

In [86]:
%ll

total 16
-rw-r--r-- 1 root 9032 Oct  5 20:35 global_population_stats_2024.csv
drwxr-xr-x 1 root 4096 Oct  2 13:50 sample_data/

In [87]:
df = pd.read_csv(filepath_or_buffer="global_population_stats_2024.csv")

In [88]:
df

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
0,Afghanistan,42.9,3.9,65.7,42.65,21.12,21.53,102.0
1,Albania,16.8,23.5,101.9,2.79,1.41,1.38,97.8
2,Algeria,30.3,10.0,19.7,46.81,22.94,23.87,104.1
3,Andorra,11.9,23.2,174.3,0.08,0.04,0.04,104.6
4,Angola,44.4,4.6,30.4,37.89,19.14,18.75,98.0
...,...,...,...,...,...,...,...,...
187,Venezuela,25.5,14.3,31.0,28.41,14.37,14.03,97.6
188,Vietnam,23.2,13.9,322.2,100.99,51.53,49.46,96.0
189,Yemen,41.1,4.0,76.9,40.58,20.03,20.56,102.7
190,Zambia,41.5,3.3,28.7,21.32,10.76,10.55,98.0
191,Zimbabwe,40.9,5.0,43.0,16.63,8.71,7.93,91.1

У нас тут есть табличка из 192 записей по 8 колонок в каждой - двумерная матрица.

In [89]:
df.head(3)

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
0,Afghanistan,42.9,3.9,65.7,42.65,21.12,21.53,102.0
1,Albania,16.8,23.5,101.9,2.79,1.41,1.38,97.8
2,Algeria,30.3,10.0,19.7,46.81,22.94,23.87,104.1

In [90]:
df.describe()

,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
count,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000
mean,26.308333,14.167188,348.131771,42.267812,21.012708,21.255156,101.186458
std,10.328998,9.106158,1969.940293,151.787795,74.169644,77.631324,16.366059
min,10.600000,3.300000,2.200000,0.010000,0.000000,0.000000,85.200000
25%,17.000000,6.100000,36.550000,2.180000,1.037500,1.082500,95.950000
50%,24.650000,11.250000,90.300000,9.455000,4.720000,4.660000,98.700000
75%,36.350000,22.250000,209.725000,32.467500,15.750000,16.387500,101.400000
max,49.000000,43.500000,25926.800000,1450.940000,702.610000,748.320000,248.200000

In [91]:
df["Country"]

0      Afghanistan
1          Albania
2          Algeria
3          Andorra
4           Angola
          ...
187      Venezuela
188        Vietnam
189          Yemen
190         Zambia
191       Zimbabwe
Name: Country, Length: 192, dtype: object

In [92]:
view = df[df["Country"] == "Russia"]
view

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
141,Russia,17.3,24.0,8.8,144.82,77.62,67.21,86.6

In [93]:
view = df[
    (df["Population Aged 0 to 14 (%)"] > 40.0) & (df["Population(in millions)"] > 30)
]
view

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
0,Afghanistan,42.9,3.9,65.7,42.65,21.12,21.53,102.0
4,Angola,44.4,4.6,30.4,37.89,19.14,18.75,98.0
44,Côte d’Ivoire,40.9,4.3,100.4,31.93,15.69,16.25,103.6
46,Democratic Republic of the Congo,46.0,4.8,48.2,109.28,55.06,54.22,98.5
116,Mozambique,44.5,4.1,44.0,34.63,17.83,16.80,94.2
125,Nigeria,41.0,4.9,255.5,232.68,115.01,117.67,102.3
163,Sudan,40.5,5.3,28.6,50.45,25.44,25.01,98.3
178,Uganda,43.5,3.5,250.3,50.02,25.21,24.81,98.4
182,Tanzania,42.5,4.5,77.4,68.56,34.58,33.98,98.3
189,Yemen,41.1,4.0,76.9,40.58,20.03,20.56,102.7

In [94]:
view = df[
    (df["Population Aged 60 and Over (%)"] > 25.0)
    & (df["Population(in millions)"] > 30)
]
view.sort_values("Population Aged 60 and Over (%)", ascending=False)

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
85,Japan,11.4,35.9,328.4,123.75,63.38,60.37,95.3
83,Italy,11.9,32.1,200.5,59.34,30.34,29.00,95.6
65,Germany,13.9,31.0,242.6,84.55,42.80,41.75,97.6
61,France,16.5,28.4,120.7,66.55,34.29,32.26,94.1
161,Spain,12.9,28.1,95.4,47.91,24.39,23.52,96.4
138,South Korea,10.6,27.4,522.7,51.72,25.90,25.81,99.7
31,Canada,15.1,26.6,4.4,39.74,20.01,19.74,98.6
135,Poland,14.8,26.3,125.9,38.54,19.87,18.67,94.0
179,Ukraine,13.9,26.3,65.4,37.86,20.26,17.60,86.9
181,United Kingdom,17.2,25.5,284.8,69.14,35.09,34.04,97.0

In [95]:
df.sort_values(by="Sex ratio (males per 100 females)", ascending=False)[:10]

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
137,Qatar,15.1,3.5,263.1,3.05,0.88,2.17,248.2
180,United Arab Emirates,16.1,3.7,155.3,11.03,3.98,7.05,177.0
128,Oman,24.7,4.3,17.1,5.28,2.00,3.29,164.6
12,Bahrain,18.7,6.7,2052.4,1.61,0.61,1.00,163.4
104,Maldives,19.6,7.5,1759.3,0.53,0.20,0.33,162.6
90,Kuwait,18.2,5.9,276.9,4.93,1.92,3.02,157.2
149,Saudi Arabia,23.8,5.2,15.8,33.96,13.40,20.56,153.4
152,Seychelles,20.0,13.2,285.4,0.13,0.06,0.07,123.0
19,Bhutan,20.9,9.6,20.6,0.79,0.37,0.42,114.8
24,Brunei,20.8,10.9,80.3,0.46,0.22,0.25,113.2

In [96]:
df.sort_values(by="Sex ratio (males per 100 females)", ascending=True)[:10]

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
139,Moldova,19.8,23.0,92.3,3.04,1.64,1.40,85.2
93,Latvia,15.4,28.8,30.1,1.87,1.00,0.87,86.4
141,Russia,17.3,24.0,8.8,144.82,77.62,67.21,86.6
7,Armenia,19.2,20.4,104.5,2.97,1.59,1.38,86.7
179,Ukraine,13.9,26.3,65.4,37.86,20.26,17.60,86.9
64,Georgia,20.8,22.0,54.8,3.81,2.03,1.77,87.3
15,Belarus,16.3,25.0,44.6,9.06,4.84,4.22,87.3
99,Lithuania,14.7,27.4,45.7,2.86,1.51,1.35,89.4
172,Tonga,35.4,9.7,160.3,0.10,0.06,0.05,89.5
151,Serbia,14.3,29.5,87.8,6.74,3.54,3.20,90.3

### Инструментарий

In [97]:
df = pd.read_csv(filepath_or_buffer="global_population_stats_2024.csv")

Получить конкретную запись:

In [98]:
df.iloc[0]

Country                              Afghanistan
Population Aged 0 to 14 (%)                 42.9
Population Aged 60 and Over (%)              3.9
Population density                          65.7
Population(in millions)                    42.65
Female Population(in millions)             21.12
Male Population(in millions)               21.53
Sex ratio (males per 100 females)          102.0
Name: 0, dtype: object

`iloc` - получение по целочисленному индексу.

In [99]:
df.sort_values(by="Population density", inplace=True, ascending=False)

In [100]:
df

,Country,Population Aged 0 to 14 (%),Population Aged 60 and Over (%),Population density,Population(in millions),Female Population(in millions),Male Population(in millions),Sex ratio (males per 100 females)
112,Monaco,13.5,43.5,25926.8,0.04,0.02,0.02,95.8
154,Singapore,11.7,19.1,8539.4,5.83,2.82,3.01,106.9
12,Bahrain,18.7,6.7,2052.4,1.61,0.61,1.00,163.4
104,Maldives,19.6,7.5,1759.3,0.53,0.20,0.33,162.6
106,Malta,13.0,26.0,1713.0,0.54,0.26,0.28,107.9
...,...,...,...,...,...,...,...,...
164,Suriname,25.6,12.2,4.1,0.63,0.32,0.32,99.8
76,Iceland,17.8,21.1,3.9,0.39,0.19,0.20,104.9
118,Namibia,37.0,5.9,3.7,3.03,1.55,1.48,95.5
8,Australia,17.8,23.5,3.5,26.71,13.46,13.25,98.5
113,Mongolia,32.2,8.7,2.2,3.48,1.74,1.73,99.4

In [101]:
df.iloc[0]

Country                               Monaco
Population Aged 0 to 14 (%)             13.5
Population Aged 60 and Over (%)         43.5
Population density                   25926.8
Population(in millions)                 0.04
Female Population(in millions)          0.02
Male Population(in millions)            0.02
Sex ratio (males per 100 females)       95.8
Name: 112, dtype: object

In [102]:
df.iloc[-1]

Country                              Mongolia
Population Aged 0 to 14 (%)              32.2
Population Aged 60 and Over (%)           8.7
Population density                        2.2
Population(in millions)                  3.48
Female Population(in millions)           1.74
Male Population(in millions)             1.73
Sex ratio (males per 100 females)        99.4
Name: 113, dtype: object

In [103]:
df.loc[[1, 70, 35], ["Population(in millions)"]]

    Population(in millions)
1                      2.79
70                    14.75
35                  1419.32

`loc` - получение по кастомным индексам - можно передавать два списка - строки и колонки.

In [104]:
df_copy = df.loc[[1, 70, 35], ["Population(in millions)"]].copy()

In [105]:
df_copy[:] = 3

In [106]:
df_copy

    Population(in millions)
1                       3.0
70                      3.0
35                      3.0

In [107]:
df_copy.loc[[1, 70, 35], ["Population(in millions)"]] = 5

In [108]:
df.loc[[1, 70, 35], ["Population(in millions)"]]

    Population(in millions)
1                      2.79
70                    14.75
35                  1419.32

In [109]:
df["Population(in millions)"].head(3)

112    0.04
154    5.83
12     1.61
Name: Population(in millions), dtype: float64

In [110]:
df[["Population(in millions)"]].head(3)

     Population(in millions)
112                     0.04
154                     5.83
12                      1.61

In [111]:
type(df[["Population(in millions)"]]), type(df["Population(in millions)"])

(pandas.core.frame.DataFrame, pandas.core.series.Series)

Видим что есть два объекта - `pandas.core.frame.DataFrame` (отвечает за саму таблицу, отсюда сокращение df) и `pandas.core.series.Series` (одномерные срезы датафреймов).

In [112]:
(
    df["Population(in millions)"].head(3).values,
    df["Population(in millions)"].head(3).index,
)

(array([0.04, 5.83, 1.61]), Index([112, 154, 12], dtype='int64'))

Создадим свой датафрейм:

In [113]:
pd.Series([1, 2, 3], index=["Red", "Green", "Blue"])

Red      1
Green    2
Blue     3
dtype: int64

In [114]:
pd.Series(1, index=["Red", "Green", "Blue"])

Red      1
Green    1
Blue     1
dtype: int64

In [115]:
s = pd.Series([1, 2, 3], index=["Red", "Green", "Blue"])
s.to_frame("Values")

       Values
Red         1
Green       2
Blue        3

In [116]:
type(s), type(s.to_frame("Values"))

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [117]:
s.loc["Red"], s.iloc[-1]

(np.int64(1), np.int64(3))

Попробуем объединить таблицы:

In [118]:
df1 = df[["Population(in millions)"]].copy()
df2 = df[["Sex ratio (males per 100 females)"]].copy()

In [119]:
df1.join(df2).head(5)

     Population(in millions)  Sex ratio (males per 100 females)
112                     0.04                               95.8
154                     5.83                              106.9
12                      1.61                              163.4
104                     0.53                              162.6
106                     0.54                              107.9

In [120]:
df1 = df[["Population(in millions)", "Country"]].copy()
df2 = df[["Sex ratio (males per 100 females)", "Country"]].copy()

In [121]:
pd.merge(df1, df2, on=["Country"], how="inner").head(5)

   Population(in millions)    Country  Sex ratio (males per 100 females)
0                     0.04     Monaco                               95.8
1                     5.83  Singapore                              106.9
2                     1.61    Bahrain                              163.4
3                     0.53   Maldives                              162.6
4                     0.54      Malta                              107.9