# Python, Семинар 4.

Поделаем некоторое количество задач по пройденным темам.

## Предварительная установка и загрузка.

Сначала загрузим ранее установленные библиотеки NumPy и Pandas.

In [ ]:
import numpy as np
import pandas as pd

Также загрузим Seaborn и два датасета для дальнейшей работы.

In [ ]:
import seaborn as sns  # sn

titanic = sns.load_dataset("titanic")
tips = sns.load_dataset("tips")

## NumPy.

### Задача 1.1. Создание диапазона.

Условие: Создай массив из чётных чисел от 0 до 20 включительно.

Вход:
```python
-
```

Выход:
```python
array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
```

In [ ]:
# Решение:

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Задача 1.2. Форма и размерность.

Условие: Создай матрицу 3x4, заполненную нулями, и выведи её форму (shape) и число осей (ndim).

Вход:
```python
-
```

Выход:
```python
shape = (3, 4), ndim = 2
```

In [ ]:
# Решение:

shape = (3, 4), ndim = 2

### Задача 1.3. Reshape.

Условие: Преврати массив [1..12] в матрицу 3x4.

Вход:
```python
[1, 2, 3, ..., 12]
```

Выход:
```python
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

In [ ]:
# Решение:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

### Задача 1.4. Срез с шагом.

Условие: Из массива [0..19] возьми каждый третий элемент, начиная с индекса 1.

Вход:
```python
array([ 0,  1,  2, ..., 19])
```

Выход:
```python
array([ 1,  4,  7, 10, 13, 16, 19])
```

In [ ]:
# Решение:

array([ 1,  4,  7, 10, 13, 16, 19])

### Задача 1.5. Булева маска.

Условие: Дан массив [-2, 5, -1, 8, 0, -3, 7]. Замени все отрицательные элементы на 0.

Вход:
```python
array([-2,  5, -1,  8,  0, -3,  7])
```

Выход:
```python
array([0, 5, 0, 8, 0, 0, 7])
```

In [ ]:
# Решение:

array([0, 5, 0, 8, 0, 0, 7])

### Задача 1.6. Среднее по осям.

Условие: Дана матрица 4x3. Найди среднее по каждой строке и по каждому столбцу.

Вход:
```python
[[ 0,  1,  2]
 [ 3,  4,  5]
 [ 6,  7,  8]
 [ 9, 10, 11]]
```

Выход:
```python
По строкам: [ 1.  4.  7. 10.]
По столбцам: [4.5 5.5 6.5]
```

In [ ]:
# Решение:

По строкам: [ 1.  4.  7. 10.]
По столбцам: [4.5 5.5 6.5]

### Задача 1.7. Broadcasting.

Условие: Дана матрица 3x4. Вычти из каждой строки её среднее значение (центрирование по строкам).

Вход:
```python
[[ 1,  2,  3,  4]
 [10, 20, 30, 40]
 [ 5,  5,  5,  5]]
```

Выход:
```python
[[-1.5 -0.5  0.5  1.5]
 [-15.  -5.   5.  15. ]
 [ 0.   0.   0.   0. ]]
```

In [ ]:
# Решение:

[[ -1.5  -0.5   0.5   1.5]
 [-15.   -5.    5.   15. ]
 [  0.    0.    0.    0. ]]

### Задача 1.8. Внешнее произведение через newaxis.

Условие: Даны два вектора a = [1, 2, 3] и b = [10, 20]. Построй матрицу их попарных произведений (без циклов).

Вход:
```python
a = [1, 2, 3]
b = [10, 20]
```

Выход:
```python
[[10 20]
 [20 40]
 [30 60]]
```

In [ ]:
# Решение:

[[10 20]
 [20 40]
 [30 60]]

### Задача 1.9. Нормализация по столбцам.

Условие: Дана матрица. Нормализуй каждый столбец так, чтобы его значения лежали в диапазоне [0, 1] (min-max нормализация). Используй broadcasting, без циклов.

Вход:
```python
[[ 1, 10, 100]
 [ 2, 20, 200]
 [ 3, 30, 300]
 [ 4, 40, 400]]
```

Выход:
```python
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]
```

In [ ]:
# Решение:

[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]

### Задача 1.10. Индексация целочисленными массивами.

Условие: Дана матрица 5x5. Выбери из неё элементы по парам индексов: (0,0), (2,3), (4,1), (1,4). Используй fancy indexing, а не цикл.

Вход:
```python
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
```

Выход:
```python
array([ 0, 13, 21,  9])
```

In [ ]:
# Решение:

[ 0 13 21  9]

## Pandas.

### Задача 2.1. Первый взгляд - Titanic.

Условие: Загрузи датасет Titanic. Выведи первые 5 строк, форму таблицы и список колонок.

Вход:
```python
-
```

Выход:
```python
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
...
shape = (891, 15)
columns = ['survived', 'pclass', 'sex', 'age', 'sibsp', ...]
```

In [ ]:
# Решение:

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
shape = (891, 15)
columns = ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

In [ ]:
# Решение:

shape = (891, 15)
columns = ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Задача 2.2. Фильтр по условию - Titanic.

Условие: Оставь только пассажиров женского пола, которые выжили. Сколько их?

Вход:
```python
-
```

Выход:
```python
Количество: 233
```

In [ ]:
# Решение:

Количество: 233

### Задача 2.3. Сортировка - Tips.

Условие: Отсортируй датасет tips по столбцу total_bill по убыванию и выведи первые 5 строк.

Вход:
```python
-
```

Выход:
```python
     total_bill    tip   sex smoker  day    time  size  tip_percent
170       50.81  10.00  Male    Yes  Sat  Dinner     3    19.681165
212       48.33   9.00  Male     No  Sat  Dinner     4    18.621974
59        48.27   6.73  Male     No  Sat  Dinner     4    13.942407
156       48.17   5.00  Male     No  Sun  Dinner     6    10.379905
182       45.35   3.50  Male    Yes  Sun  Dinner     3     7.717751
```

In [ ]:
# Решение:

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

In [ ]:
# Решение:

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

### Задача 2.4. Группировка и агрегация - Tips.

Условие: Найди средний размер чаевых (tip) для каждого дня недели (day).

Вход:
```python
-
```

Выход:
```python
day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64
```

In [ ]:
# Решение:

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [ ]:
# Решение:

/tmp/ipykernel_603/2696589815.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby("day")["tip"].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [ ]:
# Решение:

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

### Задача 2.5. Несколько агрегаций - Tips.

Условие: Для каждого дня недели посчитай средний счёт (total_bill), максимальный счёт и количество записей.

Вход:
```python
-
```

Выход:
```python
      total_bill_avg  total_bill_max  count
day                                        
Thur       17.682742           43.11     62
Fri        17.151579           40.17     19
Sat        20.441379           50.81     87
Sun        21.410000           48.17     76
```

In [ ]:
# Решение:

      total_bill_avg  total_bill_max  count
day
Thur       17.682742           43.11     62
Fri        17.151579           40.17     19
Sat        20.441379           50.81     87
Sun        21.410000           48.17     76

In [ ]:
# Решение:

      total_bill_avg  total_bill_max  count
day
Thur       17.682742           43.11     62
Fri        17.151579           40.17     19
Sat        20.441379           50.81     87
Sun        21.410000           48.17     76

### Задача 2.6. Новый столбец - Tips.

Условие: Добавь столбец tip_percent — процент чаевых от общего счёта.

Вход:
```python
-
```

Выход:
```python
     total_bill   tip  tip_percent
0         16.99  1.01     5.944673
1         10.34  1.66    16.054159
2         21.01  3.50    16.658734
...
```

In [ ]:
# Решение:

     total_bill   tip  tip_percent
0         16.99  1.01     5.944673
1         10.34  1.66    16.054159
2         21.01  3.50    16.658734
3         23.68  3.31    13.978041
4         24.59  3.61    14.680765
..          ...   ...          ...
239       29.03  5.92    20.392697
240       27.18  2.00     7.358352
241       22.67  2.00     8.822232
242       17.82  1.75     9.820426
243       18.78  3.00    15.974441

[244 rows x 3 columns]

### Задача 2.7. loc и iloc - Titanic.

Условие: Выведи строки с индексами 10, 20, 30 и только колонки age, fare, sex.

Вход:
```python
-
```

Выход:
```python
     age     fare     sex
10   4.0  16.7000  female
20  35.0  26.0000    male
30  40.0  27.7208    male
```

In [ ]:
# Решение:

     age     fare     sex
10   4.0  16.7000  female
20  35.0  26.0000    male
30  40.0  27.7208    male

In [ ]:
# Решение:

     age     fare     sex
10   4.0  16.7000  female
20  35.0  26.0000    male
30  40.0  27.7208    male

### Задача 2.8. Пропуски - Titanic.

Условие: Посчитай, сколько пропущенных значений в каждой колонке. Выведи только те колонки, где пропуски есть.

Вход:
```python
-
```

Выход:
```python
age            177
embarked         2
deck           688
embark_town      2
dtype: int64
```

In [ ]:
# Решение:

age            177
embarked         2
deck           688
embark_town      2
dtype: int64

In [ ]:
# Решение:

age            177
embarked         2
deck           688
embark_town      2
dtype: int64

### Задача 2.9. Merge двух таблиц - Tips + агрегат.

Условие: Создай две таблицы из tips:

* df1 - день недели и средний счёт,
* df2 - день недели и средние чаевые.

Объедини их по day через merge и добавь столбец с отношением средних чаевых к среднему счёту (в процентах).

Вход:
```python
-
```

Выход:
```python
    day   avg_bill   avg_tip    tip_pct
0  Thur  17.682742  2.771452  15.673201
1   Fri  17.151579  2.734737  15.944519
2   Sat  20.441379  2.993103  14.642375
3   Sun  21.410000  3.255132  15.203791
```

In [ ]:
# Решение:

    day   avg_bill   avg_tip    tip_pct
0  Thur  17.682742  2.771452  15.673201
1   Fri  17.151579  2.734737  15.944519
2   Sat  20.441379  2.993103  14.642375
3   Sun  21.410000  3.255132  15.203791

### Задача 2.10. Комплексный анализ - Titanic.

Условие: Найди для каждого класса (pclass) и пола (sex):

* процент выживших,
* средний возраст,
* количество пассажиров.

Отсортируй по проценту выживших по убыванию.

Вход:
```python
-
```

Выход:
```python
               survival_rate    avg_age  count
pclass sex                                    
1      female       0.968085  34.611765     94
2      female       0.921053  28.722973     76
3      female       0.500000  21.750000    144
...
```

In [ ]:
# Решение:

               survival_rate    avg_age  count
pclass sex
1      female       0.968085  34.611765     94
2      female       0.921053  28.722973     76
3      female       0.500000  21.750000    144
1      male         0.368852  41.281386    122
2      male         0.157407  30.740707    108
3      male         0.135447  26.507589    347

<h1>
<b>
Успехов :)
</h1>
</b>